import io
import json
import re
from datetime import datetime
from typing import Literal

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from sqlalchemy import select

from app.core.database import ResearchSession, SessionLocal

router = APIRouter()

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: Georgia, 'Times New Roman', serif; font-size: 11pt; line-height: 1.7;
         color: #1a1a1a; max-width: 700px; margin: 0 auto; padding: 48px 40px; }}
  .watermark {{ display: flex; align-items: center; gap: 10px; margin-bottom: 32px;
                padding-bottom: 16px; border-bottom: 1px solid #e5e7eb; }}
  .watermark-logo {{ width: 24px; height: 24px; background: #1a1a1a; border-radius: 6px;
                     display: flex; align-items: center; justify-content: center; }}
  .watermark-name {{ font-family: system-ui, sans-serif; font-size: 13px; font-weight: 600; color: #374151; }}
  .meta {{ font-family: system-ui, sans-serif; font-size: 10px; color: #6b7280; margin-left: auto; }}
  h1 {{ font-size: 20pt; font-weight: bold; margin: 0 0 8px; line-height: 1.3; }}
  .subtitle {{ font-family: system-ui, sans-serif; font-size: 10px; color: #6b7280; margin-bottom: 32px; }}
  h2 {{ font-size: 13pt; font-weight: bold; margin: 28px 0 10px;
        padding-bottom: 6px; border-bottom: 1px solid #e5e7eb; }}
  h3 {{ font-size: 11pt; font-weight: bold; margin: 20px 0 8px; }}
  p  {{ margin: 0 0 12px; text-align: justify; }}
  ul, ol {{ margin: 0 0 12px 20px; }}
  li {{ margin-bottom: 4px; }}
  code {{ font-family: monospace; font-size: 9pt; background: #f3f4f6; padding: 1px 4px;
          border-radius: 3px; }}
  pre  {{ background: #f3f4f6; padding: 12px; border-radius: 6px; overflow-x: auto;
          font-size: 9pt; margin: 0 0 12px; }}
  blockquote {{ border-left: 3px solid #d1d5db; padding-left: 12px; color: #6b7280; margin: 0 0 12px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 0 0 12px; font-size: 10pt; }}
  th, td {{ border: 1px solid #e5e7eb; padding: 6px 10px; text-align: left; }}
  th {{ background: #f9fafb; font-weight: bold; }}
  .sources {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; }}
  .sources h2 {{ border: none; padding: 0; margin-bottom: 12px; }}
  .source-item {{ font-family: system-ui, sans-serif; font-size: 9pt; color: #374151;
                  margin-bottom: 6px; display: flex; gap: 8px; }}
  .source-num {{ color: #6b7280; flex-shrink: 0; font-weight: 600; }}
  a {{ color: #2563eb; text-decoration: none; }}
</style>
</head>
<body>
<div class="watermark">
  <div class="watermark-logo">
    <svg viewBox="0 0 16 16" width="14" height="14" fill="white">
      <circle cx="8" cy="8" r="2"/>
      <ellipse cx="8" cy="8" rx="7" ry="3"/>
    </svg>
  </div>
  <span class="watermark-name">ResearchOS</span>
  <span class="meta">{date} · {mode} mode · {source_count} sources</span>
</div>

<h1>{title}</h1>
<div class="subtitle">Generated by ResearchOS · {date}</div>

{body}

<div class="sources">
  <h2>Sources</h2>
  {sources_html}
</div>
</body>
</html>"""


class ExportRequest(BaseModel):
    format: Literal["markdown", "pdf", "bibtex"]


async def _load_session(session_id: str) -> ResearchSession:
    async with SessionLocal() as db:
        row = await db.get(ResearchSession, session_id)
        if not row:
            raise HTTPException(status_code=404, detail="Session not found")
        return row


def _build_markdown(row: ResearchSession) -> str:
    report: str = row.report or ""
    sources = json.loads(row.sources_json or "[]")
    date = (row.created_at or datetime.utcnow()).strftime("%Y-%m-%d")
    frontmatter = (
        "---\n"
        f"title: {row.query}\n"
        f"date: {date}\n"
        f"mode: {row.mode}\n"
        f"sources: {len(sources)}\n"
        "---\n\n"
    )
    refs = "\n\n## References\n\n" + "\n".join(
        f"[{i + 1}] {s.get('title', 'Untitled')} — {s.get('url', '')}"
        for i, s in enumerate(sources)
    )
    return frontmatter + report + refs


def _build_bibtex(row: ResearchSession) -> str:
    sources = json.loads(row.sources_json or "[]")
    academic = [s for s in sources if s.get("source_type") == "academic"]
    entries: list[str] = []
    for i, s in enumerate(academic):
        url = s.get("url", "")
        title = s.get("title", "Unknown").replace("{", "").replace("}", "")
        year = (s.get("published_date") or "")[:4] or "0000"
        authors = s.get("authors", "Unknown")
        key = re.sub(r"[^a-z0-9]", "", title.lower()[:20]) + year
        entries.append(
            f"@article{{{key},\n"
            f"  title={{{title}}},\n"
            f"  author={{{authors}}},\n"
            f"  year={{{year}}},\n"
            f"  url={{{url}}},\n"
            f"  note={{arXiv}}\n"
            f"}}"
        )
    if not entries:
        return "% No academic sources found in this session."
    return "\n\n".join(entries)


def _build_pdf(row: ResearchSession) -> bytes:
    try:
        import markdown as md_lib
        from weasyprint import HTML
    except ImportError as exc:
        raise HTTPException(
            status_code=501,
            detail=f"PDF export requires weasyprint and markdown: {exc}",
        )

    sources = json.loads(row.sources_json or "[]")
    report: str = row.report or ""
    date = (row.created_at or datetime.utcnow()).strftime("%Y-%m-%d")

    # Strip the ## Sources section from the report — we render our own
    body_md = re.split(r"\n## Sources\b", report, flags=re.IGNORECASE)[0]
    body_html = md_lib.markdown(body_md, extensions=["tables", "fenced_code"])

    sources_html = "\n".join(
        f'<div class="source-item"><span class="source-num">[{i + 1}]</span>'
        f'<span>{s.get("title", "Untitled")} — <a href="{s.get("url", "")}">{s.get("url", "")}</a></span></div>'
        for i, s in enumerate(sources)
    )

    html = _HTML_TEMPLATE.format(
        title=row.query,
        date=date,
        mode=row.mode,
        source_count=len(sources),
        body=body_html,
        sources_html=sources_html,
    )

    pdf_bytes = io.BytesIO()
    HTML(string=html).write_pdf(pdf_bytes)
    return pdf_bytes.getvalue()


@router.post("/export/{session_id}")
async def export_session(session_id: str, req: ExportRequest) -> Response:
    row = await _load_session(session_id)

    if req.format == "markdown":
        content = _build_markdown(row)
        filename = f"research-{session_id[:8]}.md"
        return Response(
            content=content,
            media_type="text/markdown",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    if req.format == "bibtex":
        content = _build_bibtex(row)
        filename = f"research-{session_id[:8]}.bib"
        return Response(
            content=content,
            media_type="text/plain",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    if req.format == "pdf":
        pdf = _build_pdf(row)
        filename = f"research-{session_id[:8]}.pdf"
        return Response(
            content=pdf,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    raise HTTPException(status_code=400, detail="Unknown format")
